[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lavatmos"
authors = [{name = "cvbuchem", email = "vbuchem@strw.leidenuniv.nl"}]
dynamic = ["version", "description"]
